{"length":137,"name":"error","severity":"ERROR","code":"08P01","file":"postgres.c","line":"1682","routine":"exec_bind_message","level":"error","message":"Error in getAuthUser: bind message supplies 1 parameters, but prepared statement \"\" requires 6","stack":"error: bind message supplies 1 parameters, but prepared statement \"\" requires 6\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":137,"name":"error","severity":"ERROR","code":"08P01","file":"postgres.c","line":"1682","routine":"exec_bind_message","level":"error","message":"Error in getAuthUser: bind message supplies 1 parameters, but prepared statement \"\" requires 6","stack":"error: bind message supplies 1 parameters, but prepared statement \"\" requires 6\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":137,"name":"error","severity":"ERROR","code":"08P01","file":"postgres.c","line":"1682","routine":"exec_bind_message","level":"error","message":"Error in getAuthUser: bind message supplies 1 parameters, but prepared statement \"\" requires 6","stack":"error: bind message supplies 1 parameters, but prepared statement \"\" requires 6\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":137,"name":"error","severity":"ERROR","code":"08P01","file":"postgres.c","line":"1682","routine":"exec_bind_message","level":"error","message":"Error in getAuthUser: bind message supplies 5 parameters, but prepared statement \"\" requires 6","stack":"error: bind message supplies 5 parameters, but prepared statement \"\" requires 6\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":146,"name":"error","severity":"ERROR","code":"22007","where":"unnamed portal parameter $6 = '...'","file":"datetime.c","line":"3800","routine":"DateTimeParseError","level":"error","message":"Error in getAuthUser: invalid input syntax for type date: \"Ronan\"","stack":"error: invalid input syntax for type date: \"Ronan\"\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":97,"name":"error","severity":"ERROR","code":"22001","file":"varchar.c","line":"632","routine":"varchar","level":"error","message":"Error in getAuthUser: value too long for type character varying(8)","stack":"error: value too long for type character varying(8)\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":281,"name":"error","severity":"ERROR","code":"23502","detail":"Failing row contains (12345678900, john@example.com, password123, null, Evaluator, 1989-12-31).","schema":"public","table":"user_app","column":"complete_name","file":"execMain.c","line":"1883","routine":"ExecConstraints","level":"error","message":"Error in getAuthUser: null value in column \"complete_name\" of relation \"user_app\" violates not-null constraint","stack":"error: null value in column \"complete_name\" of relation \"user_app\" violates not-null constraint\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)"}
{"length":177,"name":"error","severity":"ERROR","code":"22007","where":"unnamed portal parameter $6 = '...'","file":"datetime.c","line":"3800","routine":"DateTimeParseError","level":"error","message":"Error in getAuthUser: invalid input syntax for type date: \"0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN\"","stack":"error: invalid input syntax for type date: \"0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN\"\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)"}
{"length":177,"name":"error","severity":"ERROR","code":"22007","where":"unnamed portal parameter $6 = '...'","file":"datetime.c","line":"3800","routine":"DateTimeParseError","level":"error","message":"Error in getAuthUser: invalid input syntax for type date: \"0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN\"","stack":"error: invalid input syntax for type date: \"0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN\"\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)"}
{"length":200,"name":"error","severity":"ERROR","code":"23505","detail":"Key (cpf)=(12345678900) already exists.","schema":"public","table":"user_app","constraint":"user_app_pkey","file":"nbtinsert.c","line":"663","routine":"_bt_check_unique","level":"error","message":"Error in getAuthUser: duplicate key value violates unique constraint \"user_app_pkey\"","stack":"error: duplicate key value violates unique constraint \"user_app_pkey\"\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":353,"name":"error","severity":"ERROR","code":"23514","detail":"Failing row contains (12545678901, mariasouza@example.com, securepassword123, Maria Souza, evaluator, 1989-12-31, 2024-11-06 17:37:44.292879, 2024-11-06 17:37:44.292879).","schema":"public","table":"user_app","constraint":"user_app_role_check","file":"execMain.c","line":"1934","routine":"ExecConstraints","level":"error","message":"Error in getAuthUser: new row for relation \"user_app\" violates check constraint \"user_app_role_check\"","stack":"error: new row for relation \"user_app\" violates check constraint \"user_app_role_check\"\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":98,"name":"error","severity":"ERROR","code":"22001","file":"varchar.c","line":"632","routine":"varchar","level":"error","message":"Error in getAuthUser: value too long for type character varying(11)","stack":"error: value too long for type character varying(11)\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":315,"name":"error","severity":"ERROR","code":"23502","detail":"Failing row contains (72772737372, test@gmail.com, 52626262622, Robeeto, null, 2024-11-06, 2024-11-06 18:05:07.373851, 2024-11-06 18:05:07.373851).","schema":"public","table":"user_app","column":"role","file":"execMain.c","line":"1883","routine":"ExecConstraints","level":"error","message":"Error in getAuthUser: null value in column \"role\" of relation \"user_app\" violates not-null constraint","stack":"error: null value in column \"role\" of relation \"user_app\" violates not-null constraint\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":315,"name":"error","severity":"ERROR","code":"23502","detail":"Failing row contains (72772737372, test@gmail.com, 52626262622, Robeeto, null, 2024-11-06, 2024-11-06 18:05:18.550037, 2024-11-06 18:05:18.550037).","schema":"public","table":"user_app","column":"role","file":"execMain.c","line":"1883","routine":"ExecConstraints","level":"error","message":"Error in getAuthUser: null value in column \"role\" of relation \"user_app\" violates not-null constraint","stack":"error: null value in column \"role\" of relation \"user_app\" violates not-null constraint\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"length":200,"name":"error","severity":"ERROR","code":"23505","detail":"Key (cpf)=(72772737372) already exists.","schema":"public","table":"user_app","constraint":"user_app_pkey","file":"nbtinsert.c","line":"663","routine":"_bt_check_unique","level":"error","message":"Error in getAuthUser: duplicate key value violates unique constraint \"user_app_pkey\"","stack":"error: duplicate key value violates unique constraint \"user_app_pkey\"\n    at /home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/pg/lib/client.js:535:17\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"Error in AuthUser: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at Object.module.exports [as sign] (/home/kleber/Development/HappyHeartProject/packages/heart-user-server/node_modules/jsonwebtoken/sign.js:111:20)\n    at UserService.<anonymous> (/home/kleber/Development/HappyHeartProject/packages/heart-user-server/src/modules/user/services/userService.ts:197:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/kleber/Development/HappyHeartProject/packages/heart-user-server/src/modules/user/services/userService.ts:5:58)"}
